name: Speedport Pro
version: "0.0.8"
slug: speedport_pro
description: Integration für Telekom Speedport Pro Router
url: https://github.com/SteveP86/HomeAssistant-Addons
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
boot: manual
host_network: true
hassio_role: admin

# Standardwerte der Konfiguration
options:
  router_ip: "192.168.2.1"
  username: "admin"
  password: ""

# Schema der Benutzer-Eingaben (nur erlaubte Typen!)
schema:
  router_ip: str
  username: str
  password: password
