name: "Speedport Pro All-in-One"
version: "0.0.1"
slug: speedport_pro_allinone
description: "Loggt sich im Speedport ein, liest DSL/LTE-Werte und erstellt Home-Assistant-Sensoren automatisch."
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
startup: services
boot: auto
init: false
options:
  router_ip: 192.168.2.1
  router_password: ""
  interval: 60
schema:
  router_ip: str
  router_password: password
  interval: int(10,300)
