name: Speedport Pro
version: "0.0.1"
slug: speedport_pro
description: Integration für Telekom Speedport Pro Router
url: https://github.com/SteveP86/HomeAssistant-Addons
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
boot: manual
host_network: true
hassio_role: admin
options:
  router_ip:
    default: "192.168.2.1"
    required: true
  username:
    default: "admin"
    required: true
  password:
    default: ""
    required: true
schema:
  type: object
  properties:
    router_ip:
      type: string
      title: Router IP-Adresse
    username:
      type: string
      title: Benutzername
    password:
      type: string
      title: Passwort
      format: password
