name: "Speedport Pro"
version: "0.0.18"
slug: "speedportpro"
description: "Speedport Pro Status-Integration"
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
init: false
hassio_api: true
hassio_role: default
options:
  router_host: "192.168.2.1"
  scan_interval: 30
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_pass: ""
  mqtt_topic_prefix: "speedport"
schema:
  router_host: str
  scan_interval: int(10,300)
  mqtt_host: str
  mqtt_port: int(1,65535)
  mqtt_user: str?
  mqtt_pass: password?
  mqtt_topic_prefix: str
ports: {}
